[[headers]]
  for = "/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"

[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"

[[redirects]]
  from = "/.well-known/apple-app-site-association"
  to = "/apple-app-site-association"
  status = 200
  force = true
